title: Glór
description: Glór site using the Just the Docs theme
theme: just-the-docs

url: https://celtic_ytd.github.io

aux_links:
  Template Repository: https://github.com/glor0/celtic_jtd

# Navigation options
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Language-specific options
defaults:
  - scope:
      path: ""
    values:
      lang: "pl"
      permalink: /:path/
  - scope:
      path: "docs/en"
    values:
      lang: "en"
      permalink: /en/:path/
  - scope:
      path: "docs/cs"
    values:
      lang: "cs"
      permalink: /cs/:path/

# Navigation structure for each language
nav:
  pl:
    - title: "Główna"
      url: /
  en:
    - title: "Main"
      url: /en/
  cs:
    - title: "Hlavna"
      url: /cs/
