title: Glór
description: Glór site using the Just the Docs theme
theme: just-the-docs

# Site URL
url: https://glor0.github.io/celtic_jtd
# Repository name here
baseurl: "/glor0"


# Auxiliary links (optional)
aux_links:
  Template Repository: https://github.com/glor0/celtic_jtd

# Enable the "docs" collection for language support
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Language-specific configuration
defaults:
  - scope:
      path: ""
    values:
      lang: "pl"
      permalink: /pl/:path/
  - scope:
      path: "docs/en"
    values:
      lang: "en"
      permalink: /en/:path/
  - scope:
      path: "docs/cs"
    values:
      lang: "cs"
      permalink: /cs/:path/

# Language-specific navigation (in header)
nav:
  pl:
    - title: "Główna"
      url: /pl/
  en:
    - title: "Main"
      url: /en/
  cs:
    - title: "Hlavna"
      url: /cs/
