title: Glór
description: Glór site using the Just the Docs theme
theme: just-the-docs

url: https://glor0.github.io/celtic_jtd

aux_links:
  Template Repository: https://github.com/glor0/celtic_jtd

# plugins:
#   - jekyll-multiple-languages-plugin

languages: ["pl", "en", "de", "cs"]
